{% set version = "1.6.5" %}

package:
  name: backports.functools_lru_cache
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/b/backports.functools_lru_cache/backports.functools_lru_cache-{{ version }}.tar.gz
  sha256: e7efcdd8cf92279bcb09fdb9b31e984ffdc96fc9f21e22ff20538884cb99b97d

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools_scm
    - backports

  run:
    - python >=3.6
    - setuptools
    - backports

test:
  imports:
    - backports.functools_lru_cache

about:
  home: https://github.com/jaraco/backports.functools_lru_cache
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: Backport of functools.lru_cache from Python 3.3 as published at ActiveState.
  doc_url: https://pypi.python.org/pypi/backports.functools_lru_cache
  dev_url: https://github.com/jaraco/backports.functools_lru_cache

extra:
  recipe-maintainers:
    - mariusvniekerk
    - stuertz
